# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mott' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Architecture
  pod 'ReactorKit'

  # Rx
  pod 'RxCocoa'
  pod 'RxSwift'

  # UI
  pod 'SnapKit'

end
